# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\UTEST\utest\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Utest(object):
    def setupUi(self, Utest):
        Utest.setObjectName("Utest")
        Utest.resize(551, 480)
        self.centralwidget = QtWidgets.QWidget(Utest)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 50, 101, 141))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 21, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 0, 21, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(110, 90, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 70, 54, 12))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 0, 231, 31))
        self.textEdit.setObjectName("textEdit")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(370, 10, 75, 23))
        self.select.setObjectName("select")
        Utest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Utest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 23))
        self.menubar.setObjectName("menubar")
        self.startmenu = QtWidgets.QMenu(self.menubar)
        self.startmenu.setObjectName("startmenu")
        self.helpmenu = QtWidgets.QMenu(self.menubar)
        self.helpmenu.setObjectName("helpmenu")
        self.setmemnu = QtWidgets.QMenu(self.menubar)
        self.setmemnu.setObjectName("setmemnu")
        Utest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Utest)
        self.statusbar.setObjectName("statusbar")
        Utest.setStatusBar(self.statusbar)
        self.menubar.addAction(self.startmenu.menuAction())
        self.menubar.addAction(self.helpmenu.menuAction())
        self.menubar.addAction(self.setmemnu.menuAction())

        self.retranslateUi(Utest)
        QtCore.QMetaObject.connectSlotsByName(Utest)

    def retranslateUi(self, Utest):
        _translate = QtCore.QCoreApplication.translate
        Utest.setWindowTitle(_translate("Utest", "Utest"))
        self.pushButton.setText(_translate("Utest", "PushButton"))
        self.pushButton_2.setText(_translate("Utest", "PushButton"))
        self.label.setText(_translate("Utest", "信息"))
        self.select.setText(_translate("Utest", "浏览"))
        self.startmenu.setTitle(_translate("Utest", "开始"))
        self.helpmenu.setTitle(_translate("Utest", "help"))
        self.setmemnu.setTitle(_translate("Utest", "设置"))
