# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\1\utest\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qsci import QsciScintilla


class Ui_Utest(object):
    def setupUi(self, Utest):
        Utest.setObjectName("Utest")
        Utest.resize(1068, 857)
        self.centralwidget = QtWidgets.QWidget(Utest)
        self.centralwidget.setObjectName("centralwidget")
        self.filewindows = QtWidgets.QTreeWidget(self.centralwidget)
        self.filewindows.setGeometry(QtCore.QRect(0, 100, 171, 481))
        self.filewindows.setObjectName("filewindows")
        self.filewindows.headerItem().setText(0, "1")
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start.setGeometry(QtCore.QRect(0, 0, 21, 23))
        self.bt_start.setObjectName("bt_start")
        self.bt_end = QtWidgets.QPushButton(self.centralwidget)
        self.bt_end.setGeometry(QtCore.QRect(40, 0, 21, 23))
        self.bt_end.setObjectName("bt_end")
        self.devices = QtWidgets.QTextBrowser(self.centralwidget)
        self.devices.setGeometry(QtCore.QRect(790, 100, 256, 481))
        self.devices.setObjectName("devices")
        self.filepath = QtWidgets.QTextEdit(self.centralwidget)
        self.filepath.setGeometry(QtCore.QRect(200, 20, 401, 31))
        self.filepath.setObjectName("filepath")
        self.bt_selectapk = QtWidgets.QPushButton(self.centralwidget)
        self.bt_selectapk.setGeometry(QtCore.QRect(600, 20, 75, 31))
        self.bt_selectapk.setObjectName("bt_selectapk")
        self.codeidea = QsciScintilla(self.centralwidget)
        self.codeidea.setGeometry(QtCore.QRect(180, 100, 601, 481))
        self.codeidea.setObjectName("codeidea")
        self.console = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(180, 600, 601, 161))
        self.console.setObjectName("console")
        self.adbconsole = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.adbconsole.setGeometry(QtCore.QRect(790, 600, 261, 161))
        self.adbconsole.setObjectName("adbconsole")
        Utest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Utest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 23))
        self.menubar.setObjectName("menubar")
        self.startmenu = QtWidgets.QMenu(self.menubar)
        self.startmenu.setObjectName("startmenu")
        self.helpmenu = QtWidgets.QMenu(self.menubar)
        self.helpmenu.setObjectName("helpmenu")
        self.setmemnu = QtWidgets.QMenu(self.menubar)
        self.setmemnu.setObjectName("setmemnu")
        Utest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Utest)
        self.statusbar.setObjectName("statusbar")
        Utest.setStatusBar(self.statusbar)
        self.menubar.addAction(self.startmenu.menuAction())
        self.menubar.addAction(self.helpmenu.menuAction())
        self.menubar.addAction(self.setmemnu.menuAction())

        self.retranslateUi(Utest)
        QtCore.QMetaObject.connectSlotsByName(Utest)

    def retranslateUi(self, Utest):
        _translate = QtCore.QCoreApplication.translate
        Utest.setWindowTitle(_translate("Utest", "Utest"))
        self.bt_start.setText(_translate("Utest", "PushButton"))
        self.bt_end.setText(_translate("Utest", "PushButton"))
        self.bt_selectapk.setText(_translate("Utest", "浏览"))
        self.startmenu.setTitle(_translate("Utest", "开始"))
        self.helpmenu.setTitle(_translate("Utest", "help"))
        self.setmemnu.setTitle(_translate("Utest", "设置"))
